export const REQUEST_STATES = {
    IDLE: "IDLE",
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
}


export const COMMENT_STATUS = {
    POSTED: 'POSTED',
    DRAFT: 'DRAFT'
}

export const DOMAIN_CREATION_STATUS = {
    NOT_STARTED: "NOT_STARTED",
    IN_PROCESS: "IN_PROCESS",
    COMPLETE: "COMPLETE"
}

